title: "Seju Lee"
description: "경제학 공부를 위한 개인 저장소"
url: "https://leeseju.github.io"
baseurl: "/leeseju"   # leeseju 리포 → 프로젝트 페이지 맞음

# ★ 핵심: theme가 아니라 remote_theme 사용
remote_theme: "mmistakes/minimal-mistakes"

minimal_mistakes_skin: "default"

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-include-cache   # minimal-mistakes가 권장하는 플러그인
